spring.application.name=nexa_mobility
spring.datasource.url=jdbc:mysql://localhost:3306/api?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# Configurações do Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
